version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:7000:3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      shared:
        ipv4_address: 172.18.0.10
    container_name: ChainFlip-Analyzer
    restart: always
networks:
  shared:
    external: true
