version: '3.8'
services:
  chainflip-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:7000:3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      shared:
        ipv4_address: 172.18.0.10
    container_name: ChainFlip-Analyzer
    restart: always
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:3000'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  shared:
    external: true
